import { Injectable } from '@angular/core';
import { Insta} from '../model/instagram.model';

@Injectable({
  providedIn: 'root',
})
export class InstagramService {
  city: Insta[] = [
    {
      pseudo: 'Goku',
      titre: 'Paysage Touristique Québécois',
      date: new Date(),
      description:
        'Un magnifique Lac au large du Québec pour explorer la beauté de la nature',
      localisation: 'Québec',
      nbrAime: 15,
      imageUrl: '../assets/paysage_01.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique', 'Sublime'],
    },
    {
      pseudo: 'Naruto',
      titre: 'Paysage Touristique Croate',
      date: new Date(),
      description: 'Photo de la Ville Croate de Rovinj',
      localisation: 'Croate',
      nbrAime: 10,
      imageUrl: '../assets/paysage_02.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Luffy',
      titre: 'Paysage Touristique Français',
      date: new Date(),
      description: 'Chaîne de montagnes',
      localisation: 'France',
      nbrAime: 10,
      imageUrl: '../assets/paysage_03.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Matsumoto',
      titre: 'Paysage Touristique Marocain',
      date: new Date(),
      description: 'Port Touristique au large des côtes marocaines',
      localisation: 'Maroc',
      nbrAime: 10,
      imageUrl: '../assets/paysage_04.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Esdeath',
      titre: 'Paysage Touristique Indien',
      date: new Date(),
      description: "Enceinte d'un chateau en Inde",
      localisation: 'Inde',
      nbrAime: 20,
      imageUrl: '../assets/paysage_05.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Aizen',
      titre: 'Paysage Touristique Français',
      date: new Date(),
      description: 'Forêt classée dans la ville Bourgogne',
      localisation: 'Bourgogne',
      nbrAime: 10,
      imageUrl: '../assets/paysage_06.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Madara',
      titre: 'Paysage Touristique Canadien',
      date: new Date(),
      description: 'Chute de Niagara',
      localisation: 'Canada',
      nbrAime: 10,
      imageUrl: '../assets/paysage_07.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Zaraki',
      titre: 'Paysage Touristique Haïtien',
      date: new Date(),
      description: 'Chaîne de montagnes haïtien',
      localisation: 'Haïti',
      nbrAime: 15,
      imageUrl: '../assets/paysage_08.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Albedo',
      titre: 'Paysage Touristique Haïtien',
      date: new Date(),
      description: 'Plag balnière',
      localisation: 'Haïti',
      nbrAime: 20,
      imageUrl: '../assets/paysage_09.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'AllMight',
      titre: 'Paysage Touristique Norvègien',
      date: new Date(),
      description: 'Plaine rurale',
      localisation: 'Norvège',
      nbrAime: 10,
      imageUrl: '../assets/paysage_10.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Jiren',
      titre: 'Paysage Touristique Marocain',
      date: new Date(),
      description: "Photo d'un village marocain",
      localisation: 'Maroc',
      nbrAime: 16,
      imageUrl: '../assets/paysage_11.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Oppai',
      titre: 'Paysage Touristique Indénosien',
      date: new Date(),
      description: 'Place balnière',
      localisation: 'Indonésie',
      nbrAime: 10,
      imageUrl: '../assets/paysage_12.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Itachi',
      titre: 'Paysage Touristique Papouasien',
      date: new Date(),
      description: "Hôtel sur l'océan indien",
      localisation: 'Papouasie Nouvelle Guinée',
      nbrAime: 30,
      imageUrl: '../assets/paysage_13.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Oshiri',
      titre: 'Paysage Touristique Béninois',
      date: new Date(),
      description: 'Cascade',
      localisation: 'Bénin',
      nbrAime: 10,
      imageUrl: '../assets/paysage_14.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Shine',
      titre: 'Paysage Touristique Grecque',
      date: new Date(),
      description: 'Ville Côtière',
      localisation: 'Grèce',
      nbrAime: 10,
      imageUrl: '../assets/paysage_15.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Bakayaro',
      titre: 'Paysage Touristique Autrichien',
      date: new Date(),
      description: "Vue d'un lac",
      localisation: 'Autriche',
      nbrAime: 10,
      imageUrl: '../assets/paysage_16.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Doflamingo',
      titre: 'Paysage Touristique Serbe',
      date: new Date(),
      description: "Vue aérienne d'une ville Serbe",
      localisation: 'Serbie',
      nbrAime: 20,
      imageUrl: '../assets/paysage_17.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Katakuri',
      titre: 'Paysage Touristique Sud Coréen',
      date: new Date(),
      description: 'Busan, Deuxième plus grande ville',
      localisation: 'Corée du Sud',
      nbrAime: 20,
      imageUrl: '../assets/paysage_18.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Boa_Hancock',
      titre: 'Paysage Touristique Sud Coréen',
      date: new Date(),
      description: 'Jeonju, Ville situé au sud-ouest de la capitale',
      localisation: 'Corée du Sud',
      nbrAime: 30,
      imageUrl: '../assets/paysage_19.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Shirayoshi',
      titre: 'Paysage Touristique Sud Coréen',
      date: new Date(),
      description: 'Vue du fleuve Han situé à Séoul',
      localisation: 'Corée du Sud',
      nbrAime: 20,
      imageUrl: '../assets/paysage_20.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
  ];

  getAllSnap() {
    return this.city;
  }
  constructor() {}
}
